export const ACCOUNT_LIST_REQUEST = 'ACCOUNT_LIST_REQUEST';
export const ACCOUNT_LIST_SUCCESS = 'ACCOUNT_LIST_SUCCESS';
export const ACCOUNT_LIST_FAILURE = 'ACCOUNT_LIST_FAILURE';

export const TIMELINE_LIST_REQUEST = 'TIMELINE_LIST_REQUEST';
export const TIMELINE_LIST_SUCCESS = 'TIMELINE_LIST_SUCCESS';
export const TIMELINE_LIST_FAILURE = 'TIMELINE_LIST_FAILURE';

